### ISSUE TITLE
MantineProvider ERROR

### ISSUE THREAD

**Issue by arosayru** [ZainRk/Full-stack-real-estate-youtube#11]
Uncaught Error: @mantine/core: MantineProvider was not found in component tree, make sure you have it in your app
    at useMantineTheme (MantineThemeProvider.tsx:9:11)
    at useProps (use-props.ts:21:17)
    at Menu (Menu.tsx:58:17)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20074:13)
    at beginWork (react-dom.development.js:21587:16)
    at beginWork$1 (react-dom.development.js:27426:14)
    at performUnitOfWork (react-dom.development.js:26557:12)
    at workLoopSync (react-dom.development.js:26466:5)
    at renderRootSync (react-dom.development.js:26434:7)

**Comment by sakshi-jaiswal03** [comment]
were u able to solve this?

**Comment by pandeyharsh81r** [comment]
Wrap your entire app within mantine provider tag just as shown below and then let me know if it resolved this issue or not.
(Also don't forget to import MantineProvider as stated below)

```
import { MantineProvider } from "@mantine/core;
<MantineProvider theme={{ primaryColor: 'blue' }}>
        <App />
</MantineProvider>
```
