### ISSUE TITLE
errors.tsx:9 Uncaught (in promise) Error: Service not found: http://localhost:8000

### ISSUE THREAD

**Issue by arosayru** [ZainRk/Full-stack-real-estate-youtube#12]

**Comment by ankit705yadav** [comment]
can you be more specific? copy of whole error message will do

**Comment by arosayru** [comment]
I solved it brdh...Thank you

**Comment by ankit705yadav** [comment]
> I solved it brdh...Thank you

Did you get everything working?

**Comment by arosayru** [comment]
Yes brdh

**Comment by ankit705yadav** [comment]
> Yes brdh

add property feature working?

**Comment by Ayush3366** [comment]
please help me how did you solved that , i am getting same error -- 

Uncaught (in promise) Error: Service not found: http://localhost:8000
    at new OAuthError2 (errors.tsx:9:11)
    at utils.tsx:17:14
    at auth0-provider.tsx:237:15
    at step (@auth0_auth0-react.js?v=afc06b3d:144:19)
    at Object.throw (@auth0_auth0-react.js?v=afc06b3d:91:14)
    at rejected (@auth0_auth0-react.js?v=afc06b3d:69:32)

**Comment by monira-ahmed** [comment]
> I solved it brdh...Thank you

can help me how did you solve it !!

**Comment by Greviansonula** [comment]
> I solved it brdh...Thank you

@arosayru please could you share some insights on how you were able to solve the service not found error? Facing the same issue and can't figure out the problem
<img width="960" alt="image" src="https://github.com/ZainRk/Full-stack-real-estate-youtube/assets/55585900/3db17326-d8b4-4c7a-8d97-08d51a0e0740">

**Comment by Greviansonula** [comment]
@monira-ahmed and anyone facing the above issue, you can fix it by creating an api with the identifier as the URL in question above. The primary issue is that identifier parameter we passed as the audience is not linked to an API that we registered in the dashboard. see screenshot 
<img width="960" alt="image" src="https://github.com/ZainRk/Full-stack-real-estate-youtube/assets/55585900/481d7ea3-b5c7-4ff4-b09d-ab4cbabaf4b0">

**Comment by monira-ahmed** [comment]
> @monira-ahmed and anyone facing the above issue, you can fix it by creating an api with the identifier as the URL in question above. The primary issue is that identifier parameter we passed as the audience is not linked to an API that we registered in the dashboard. see screenshot <img alt="image" width="960" src="https://private-user-images.githubusercontent.com/55585900/293581845-481d7ea3-b5c7-4ff4-b09d-ab4cbabaf4b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMjQ0NjAsIm5iZiI6MTcwNDEyNDE2MCwicGF0aCI6Ii81NTU4NTkwMC8yOTM1ODE4NDUtNDgxZDdlYTMtYjVjNy00ZmY0LWIwOWQtYWI0Y2JhYmFmNGIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDE1NDkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhNmVlMGI3ZGI5MDJiOTBiYmY4MTIxOTFlYzUyMGJkMGIyMDE1MDZhMGI0NmUyYjEzYmMzNjAyNjBiMjdmNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jwQ9oUOylnJ7Aq3v0gEnUJ_1agy5CUwzIxDJJdVczEI">
still not working

**Comment by Greviansonula** [comment]
@monira-ahmed did you use the identifier as the server address? I did this and worked perfectly fine for me

**Comment by monira-ahmed** [comment]
> @monira-ahmed did you use the identifier as the server address? I did this and worked perfectly fine for me

![Screenshot 2024-01-01 2257461](https://github.com/ZainRk/Full-stack-real-estate-youtube/assets/153394092/901eacf9-83e4-48b4-a27f-a7977488516a)
like this!!!

**Comment by Shehan-lakshitha** [comment]
> I solved it brdh...Thank you

Could you help to solve the issue

**Comment by Shehan-lakshitha** [comment]
> > @monira-ahmed did you use the identifier as the server address? I did this and worked perfectly fine for me
> 
> ![Screenshot 2024-01-01 2257461](https://private-user-images.githubusercontent.com/153394092/293606946-901eacf9-83e4-48b4-a27f-a7977488516a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzNTUyODAsIm5iZiI6MTcwOTM1NDk4MCwicGF0aCI6Ii8xNTMzOTQwOTIvMjkzNjA2OTQ2LTkwMWVhY2Y5LTgzZTQtNDhiNC1hMjdmLWE3OTc3NDg4NTE2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMlQwNDQ5NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTBjNDY2NjRhZWQ4NzhmNDVmMGM3ODYyNjIyODg0N2M5MWNhZDI5OTdlMDRjOWNhZTc1ZDcwMzg4YzU0MmRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-JhuJ3MkR6rPfProlXBAMMwBWuNL1D9FRqIhZR6Ozjk) like this!!!

Could please help me to fix this issue
