### ISSUE TITLE
Service not found error

### ISSUE THREAD

**Issue by Naveen3251** [ZainRk/Full-stack-real-estate-youtube#14]
Uncaught (in promise) Error: Service not found: http://localhost:8000
    at new OAuthError2 (errors.tsx:9:11)
    at utils.tsx:17:14
    at auth0-provider.tsx:237:15
    at step (@auth0_auth0-react.js?v=bf31ceae:144:19)
    at Object.throw (@auth0_auth0-react.js?v=bf31ceae:91:14)
    at rejected (@auth0_auth0-react.js?v=bf31ceae:69:32)
OAuthError2 @ errors.tsx:9
(anonymous) @ utils.tsx:17
(anonymous) @ auth0-provider.tsx:237
step @ @auth0_auth0-react.js?v=bf31ceae:144
(anonymous) @ @auth0_auth0-react.js?v=bf31ceae:91
rejected @ @auth0_auth0-react.js?v=bf31ceae:69
await in rejected (async)
(anonymous) @ Layout.jsx:45
commitHookEffectListMount @ react-dom.development.js:23150
commitPassiveMountOnFiber @ react-dom.development.js:24926
commitPassiveMountEffects_complete @ react-dom.development.js:24891
commitPassiveMountEffects_begin @ react-dom.development.js:24878
commitPassiveMountEffects @ react-dom.development.js:24866
flushPassiveEffectsImpl @ react-dom.development.js:27039
flushPassiveEffects @ react-dom.development.js:26984
performSyncWorkOnRoot @ react-dom.development.js:26076
flushSyncCallbacks @ react-dom.development.js:12042
commitRootImpl @ react-dom.development.js:26959
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25981
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533

**Comment by Prachigetgit** [comment]
did uh find its solution??

**Comment by Naveen3251** [comment]
No i couldnt resolve the error i just stopped this project because of other project commitments. could you help me?
