### ISSUE TITLE
Service not found bug

### ISSUE THREAD

**Issue by Ak-Amey** [ZainRk/Full-stack-real-estate-youtube#4]
errors.tsx:9 Uncaught (in promise) Error: Service not found: http://localhost:8000
    at new OAuthError2 (errors.tsx:9:11)
    at utils.tsx:17:14
    at auth0-provider.tsx:237:15
    at step (@auth0_auth0-react.js?v=a81887f1:144:19)
    at Object.throw (@auth0_auth0-react.js?v=a81887f1:91:14)
    at rejected (@auth0_auth0-react.js?v=a81887f1:69:32)

**Comment by Manoj735** [comment]
same error

**Comment by rohitkarki9980** [comment]
same error sir why

**Comment by rohitkarki9980** [comment]
it came after auth0Config is added in file and when I am adding jwtcheck it shows error like this

**Comment by rohitkarki9980** [comment]
whoever face this error please go to api.js in utils and add base url:"http://localhost:8000/api
thanks me later

**Comment by ankit705yadav** [comment]
> whoever face this error please go to api.js in utils and add base url:"http://localhost:8000/api thanks me later

I'm still getting same error

**Comment by rohitkarki9980** [comment]
check all the api is loaded through post man again or not?

**Comment by ankit705yadav** [comment]
> check all the api is loaded through post man again or not?

it worked thankYou

**Comment by monira-ahmed** [comment]
> check all the api is loaded through post man again or not?

how!!!

**Comment by Greviansonula** [comment]
Refer here for the fix https://github.com/ZainRk/Full-stack-real-estate-youtube/issues/12#issuecomment-1873278964
